plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}
version = mod_version
group = mod_group_id
base { archivesName = mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)
repositories { mavenCentral() }
minecraft {
    mappings channel: 'official', version: minecraft_version
    runs {
        client { workingDirectory project.file('run'); mods { netflared { source sourceSets.main } } }
        server { workingDirectory project.file('run'); args '--nogui'; mods { netflared { source sourceSets.main } } }
    }
}
dependencies { minecraft "net.minecraftforge:forge:" + forge_version }
tasks.withType(ProcessResources).configureEach {
    def replaceProperties = [minecraft_version:minecraft_version, minecraft_version_range:minecraft_version_range, forge_version:forge_version, mod_id:mod_id, mod_name:mod_name, mod_license:mod_license, mod_version:mod_version, mod_authors:mod_authors, mod_description:mod_description]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) { expand replaceProperties }
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
