org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[4,)

mod_id=netflared
mod_name=Netflared
mod_license=MIT
mod_version=1.3.9+neoforge.1.21.1
mod_group_id=com.netflared
mod_authors=MatějPCs
mod_description=Client-side Cloudflare Access tunnel manager for Minecraft.
